#!/bin/bash
for f in graphs/*.dot
do
	p=${f%.dot}
	p=${p#graphs/}
	o="renders/$p.png";
	if [ $f -nt $o ]
		then
			echo "dot -Tpng \"$f\" -o \"$o\""
			dot -Tpng "$f" -o "$o"
	fi

	`open renders`
done
